/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const SOCIAL_LOGIN_USER = "SOCIAL_LOGIN_USER";
export const SOCIAL_LOGIN_USER_SUCCESS = "SOCIAL_LOGIN_USER_SUCCESS";
export const SOCIAL_LOGIN_USER_ERROR = "SOCIAL_LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const USERS_LISTING = 'USERS_LISTING';
export const USERS_LISTING_SUCCESS = 'USERS_LISTING_SUCCESS';
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS';
export const CHANGE_USER_STATUS_SUCCESS = 'CHANGE_USER_STATUS_SUCCESS';
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";
/* CMS */
export const CMS_LISTING = 'CMS_LISTING';
export const CMS_LISTING_SUCCESS = 'CMS_LISTING_SUCCESS';
export const CREATE_EDIT_CMS = 'CREATE_EDIT_CMS';
export const CREATE_EDIT_CMS_SUCCESS = 'CREATE_EDIT_CMS_SUCCESS';
export const GET_CMS = 'GET_CMS';
export const GET_CMS_SUCCESS = 'GET_CMS_SUCCESS';


export const FETCH_ADMIN_PROFILE = "FETCH_ADMIN_PROFILE";
export const FETCH_ADMIN_PROFILE_SUCCESS = "FETCH_ADMIN_PROFILE_SUCCESS";
export const ADD_UPDATE_ADMIN_PROFILE = "ADD_UPDATE_ADMIN_PROFILE";
export const ADD_UPDATE_ADMIN_PROFILE_SUCCESS = "ADD_UPDATE_ADMIN_PROFILE_SUCCESS";

export const FETCH_Category  = "FETCH_Category";
export const FETCH_Category_SUCCESS = "FETCH_Category_SUCCESS";
export const FETCH_Category_ERROR = "FETCH_Category_ERROR";
export const ADD_UPDATE_Category = "ADD_UPDATE_Category";
export const ADD_UPDATE_Category_SUCCESS = "ADD_UPDATE_Category_SUCCESS";
export const ADD_UPDATE_Category_ERROR = "ADD_UPDATE_Category_ERROR";

export const FETCH_CONTENT  = "FETCH_CONTENT";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_ERROR = "FETCH_CONTENT_ERROR";
export const ADD_UPDATE_CONTENT = "ADD_UPDATE_CONTENT";
export const ADD_UPDATE_CONTENT_SUCCESS = "ADD_UPDATE_CONTENT_SUCCESS";
export const ADD_UPDATE_CONTENT_ERROR = "ADD_UPDATE_CONTENT_ERROR";
 
export * from './category/actions';
export * from "./menu/actions";
export * from "./user/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from './content/actions';